# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/wwx/CLionProjects/hotspot-dev

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/wwx/CLionProjects/hotspot-dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/wwx/CLionProjects/hotspot-dev && $(CMAKE_COMMAND) -E cmake_progress_start /home/wwx/CLionProjects/hotspot-dev/CMakeFiles /home/wwx/CLionProjects/hotspot-dev/src/share/tools/launcher/CMakeFiles/progress.marks
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f CMakeFiles/Makefile2 src/share/tools/launcher/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/wwx/CLionProjects/hotspot-dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f CMakeFiles/Makefile2 src/share/tools/launcher/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f CMakeFiles/Makefile2 src/share/tools/launcher/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f CMakeFiles/Makefile2 src/share/tools/launcher/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/wwx/CLionProjects/hotspot-dev && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
src/share/tools/launcher/CMakeFiles/java.dir/rule:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f CMakeFiles/Makefile2 src/share/tools/launcher/CMakeFiles/java.dir/rule
.PHONY : src/share/tools/launcher/CMakeFiles/java.dir/rule

# Convenience name for target.
java: src/share/tools/launcher/CMakeFiles/java.dir/rule

.PHONY : java

# fast build rule for target.
java/fast:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/build
.PHONY : java/fast

java.o: java.c.o

.PHONY : java.o

# target to build an object file
java.c.o:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java.c.o
.PHONY : java.c.o

java.i: java.c.i

.PHONY : java.i

# target to preprocess a source file
java.c.i:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java.c.i
.PHONY : java.c.i

java.s: java.c.s

.PHONY : java.s

# target to generate assembly for a file
java.c.s:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java.c.s
.PHONY : java.c.s

java_md.o: java_md.c.o

.PHONY : java_md.o

# target to build an object file
java_md.c.o:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java_md.c.o
.PHONY : java_md.c.o

java_md.i: java_md.c.i

.PHONY : java_md.i

# target to preprocess a source file
java_md.c.i:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java_md.c.i
.PHONY : java_md.c.i

java_md.s: java_md.c.s

.PHONY : java_md.s

# target to generate assembly for a file
java_md.c.s:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/java_md.c.s
.PHONY : java_md.c.s

jli_util.o: jli_util.c.o

.PHONY : jli_util.o

# target to build an object file
jli_util.c.o:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/jli_util.c.o
.PHONY : jli_util.c.o

jli_util.i: jli_util.c.i

.PHONY : jli_util.i

# target to preprocess a source file
jli_util.c.i:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/jli_util.c.i
.PHONY : jli_util.c.i

jli_util.s: jli_util.c.s

.PHONY : jli_util.s

# target to generate assembly for a file
jli_util.c.s:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/jli_util.c.s
.PHONY : jli_util.c.s

wildcard.o: wildcard.c.o

.PHONY : wildcard.o

# target to build an object file
wildcard.c.o:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/wildcard.c.o
.PHONY : wildcard.c.o

wildcard.i: wildcard.c.i

.PHONY : wildcard.i

# target to preprocess a source file
wildcard.c.i:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/wildcard.c.i
.PHONY : wildcard.c.i

wildcard.s: wildcard.c.s

.PHONY : wildcard.s

# target to generate assembly for a file
wildcard.c.s:
	cd /home/wwx/CLionProjects/hotspot-dev && $(MAKE) -f src/share/tools/launcher/CMakeFiles/java.dir/build.make src/share/tools/launcher/CMakeFiles/java.dir/wildcard.c.s
.PHONY : wildcard.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... java"
	@echo "... rebuild_cache"
	@echo "... java.o"
	@echo "... java.i"
	@echo "... java.s"
	@echo "... java_md.o"
	@echo "... java_md.i"
	@echo "... java_md.s"
	@echo "... jli_util.o"
	@echo "... jli_util.i"
	@echo "... jli_util.s"
	@echo "... wildcard.o"
	@echo "... wildcard.i"
	@echo "... wildcard.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/wwx/CLionProjects/hotspot-dev && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

