/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class J2C */

#ifndef _Included_J2C
#define _Included_J2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     J2C
 * Method:    write2proc
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_J2C_write2proc
  (JNIEnv * env, jclass clazz, jlong pid);

#ifdef __cplusplus
}
#endif
#endif
